### ISSUE TITLE
Failed to install Octopus CLI

### ISSUE THREAD

**Issue by maulemon** [OctopusDeploy/install-octopus-cli-action#139]
**Describe the bug**
Failed to install latest Octopus CLI

**To Reproduce**
Workflow
````yaml
      - name: Install Octopus CLI
        uses: OctopusDeploy/install-octopus-cli-action@v1.1.7
        with:
          version: latest
  ````

Fails to execute with the following error:
`Expand-Archive :  is not a supported archive file format. .zip is the only supported archive file format.`

**Expected behavior**
Installation of Octopus CLI should be successful

**Screenshots**
![image](https://user-images.githubusercontent.com/8656471/135728865-3297b8d2-ec87-4349-a2c6-2492a4c844b1.png)

**Desktop (please complete the following information):**
 - OS: Windows self-hosted runner
