### ISSUE TITLE
Install action is not getting latest cli version

### ISSUE THREAD

**Issue by justin-newman** [OctopusDeploy/install-octopus-cli-action#273]
**Describe the bug**
Using `v1.1.10` of this action, passing latest into the version input is still getting v7.4.3663 of the cli.
Latest seems to be `v9.0.0` per octopus.com/downloads

**To Reproduce**
Use the following:

```
      - name: Install Octopus CLI
        uses: OctopusDeploy/install-octopus-cli-action@v1.1.10
        with:
          version: latest
```

**Expected behavior**
Version 9.0.0 should be downloaded, installed, and used

**Screenshots**

![image](https://user-images.githubusercontent.com/23383538/161664087-878071e0-24bd-4387-8b02-a0c352b27b73.png)

**Additional context**
This is running on a self-hosted Windows Server 2019 machine.
Looks like there is a .json file living at https://download.octopusdeploy.com/octopus-tools/latest.json that is still referencing v7.4.3663

I'm not sure where that file is located or I would see about making a PR to update it.
