### ISSUE TITLE
API rate limit exceeded

### ISSUE THREAD

**Issue by selectblinds-mattd** [OctopusDeploy/install-octopus-cli-action#390]
**Describe the bug**
When using this action often, we intermittently get an error message about API throttling. We are not using this maliciously at all and the rate at which we build should be within the API limits.

Error: HttpClientError: API rate limit exceeded for #.#.#.#. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)

**To Reproduce**
1. Use action enough to hit limit (not sure how often that is)

**Expected behavior**
I expect that the API call will not be rate limited.

**Screenshots**
![image](https://user-images.githubusercontent.com/98845025/216164319-c64a2ea3-ea7c-42fd-9720-6cd949622c48.png)

**Additional context**
While looking through the code for the action it looks like it uses the github api to get the latest release. I don't see how it's sending any authentication which, according to the error message, may increase the api limits.

https://github.com/OctopusDeploy/install-octopus-cli-action/blob/main/src/octopus-cli.ts

```
18  const releasesUrl = `https://api.github.com/repos/OctopusDeploy/cli/releases
...
59  const releasesResponse = (await http.getJson<GitHubRelease[]>(releasesUrl)).result
```

**Comment by jbristowe** [comment]
Thanks for submitting this issue, @selectblinds-mattd. We've started a discussion about this and we will provide an update to this issue if/when we have reached a conclusion on the best way to resolve it.

In the meantime, would you mind sharing with me why you're using the CLI since your workflow is using the v3 of our GitHub Actions? Are you running a custom script? Is there something you need that we don't cover in our GitHub Actions?

**Comment by selectblinds-mattd** [comment]
@jbristowe , we are using the CLI to package up the artifacts that our build process generates. 

Here is an example of what I mean:

```
      - name: Install Octopus CLI
        uses: OctopusDeploy/install-octopus-cli-action@v3.0.0
        env:
          OCTOPUS_URL: ${{ secrets.OCTOPUS_SERVER }}
          OCTOPUS_API_KEY: ${{ secrets.OCTOPUS_APIKEY }}
      
      - name: Package published files
        run: octopus package zip create --id site --version ${{ steps.release.outputs.version }} --base-path ${{ github.workspace }}/publish --out-folder ${{ github.workspace }}/package
        env:
          OCTOPUS_URL: ${{ secrets.OCTOPUS_SERVER }}
          OCTOPUS_API_KEY: ${{ secrets.OCTOPUS_APIKEY }}
```

If there is a better way to do this that doesn't requires the CLI, please let me know.
