### ISSUE TITLE
Octopus CLI breaks in Github Actions, seemingly because https://raw.githubusercontent.com/OctopusDeploy/cli/main/releases.json doesn't contain a version field (anymore?)

### ISSUE THREAD

**Issue by philipkaare** [OctopusDeploy/install-octopus-cli-action#450]
**Describe the bug**
Octopus CLI is not able to install in GHA. 

**To Reproduce**
Try to install octopus cli in GHA. 

**Expected behavior**
It should install. 

**Screenshots**
![image](https://github.com/OctopusDeploy/install-octopus-cli-action/assets/2283775/cedb9670-acbe-40f1-853a-a73a180d4b8f)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Edge

**Additional context**
I think the problem is at: https://github.com/OctopusDeploy/install-octopus-cli-action/blob/main/src/octopus-cli.ts#L60 where the file is downloaded and parsed. It looks like a version field is expected which seems to be missing from the file.

**Comment by pvancoeverden** [comment]
We've found a workaround by downgrading the CLI action to v1.1.10 (v1.2.x breaks)

```
      - name: Install Octopus CLI
        uses: OctopusDeploy/install-octopus-cli-action@v1.1.10
        with:
          version: 9.1.7
````

Of course it would be better to upgrade to v3, but this requires more pipeline changes.
