### ISSUE TITLE
Version could not be found

### ISSUE THREAD

**Issue by abelyakov-hhglobal** [OctopusDeploy/install-octopus-cli-action#495]
**Describe the bug**
When specifying the version in the action, it doesn't work and fails with the following error:
> Error: Error: A version satisfying '2.8.0' could not be found.
> Error: Error: Failed to resolve endpoint URL to download: undefined

**To Reproduce**
Here is how I used it:
```
    - name: Install Octopus CLI
      uses: OctopusDeploy/install-octopus-cli-action@v3
      with:
        version: 2.8.1
```

**Screenshots**
<img width="597" alt="Screenshot 2024-09-16 at 10 28 48" src="https://github.com/user-attachments/assets/1e9685f3-c72a-4fff-ac1e-c5883a0b8b04">

**Additional context**
I'm running on the default GitHub runners, using `runs-on: ubuntu-latest`.
