### ISSUE TITLE
Support Octopus CLI version 2.15.0

### ISSUE THREAD

**Issue by vaiddas** [OctopusDeploy/install-octopus-cli-action#523]
**Is your feature request related to a problem? Please describe.**
Yes, it's related to the problem. 

Recently, Octopus CLI Team has added support for "progress" flag.
https://github.com/OctopusDeploy/cli/issues/363#event-16304704572
https://github.com/OctopusDeploy/cli/pull/483
This would let us pipe server task IDs from the release deploy command to task wait to view detailed task logs. 
https://octopus.com/docs/octopus-rest-api/cli/octopus-task-wait

but it appears that Octopus CLI action still uses an old version of Octopus CLI so this flag is not yet available if using GitHub action. 

**Describe the solution you'd like**
Octopus CLI action should  have an option to install 2.15.0

**Describe alternatives you've considered**
No alternative

**Additional context**
Here is what we see when using:
```
- name: Install Octopus CLI
        uses: OctopusDeploy/install-octopus-cli-action@v3
        with:
          version: 'latest'
```

Logs:

> Run OctopusDeploy/install-octopus-cli-action@v3
> Latest version available: 2.14.2
> ✓ Octopus CLI version found: 2.14.2
> ⬇️ Downloading Octopus CLI 2.[14]
> 📦 Extracting Octopus CLI 2.14.2...
